from sqlalchemy import BigInteger, Boolean, Column, Date, DateTime, Double, MetaData, Numeric, String, Table, Text
from sqlalchemy.orm.base import Mapped

metadata = MetaData()


t_sage_intacct__ap_ar_enhanced = Table(
    'sage_intacct__ap_ar_enhanced', metadata,
    Column('document_id', Text),
    Column('document_item_id', Text),
    Column('document_type', Text),
    Column('entry_date_at', Date),
    Column('entry_description', String),
    Column('amount', Double(53)),
    Column('currency', String(256)),
    Column('due_in_days', BigInteger),
    Column('item_id', Text),
    Column('item_name', String(256)),
    Column('line_no', BigInteger),
    Column('line_item', Boolean),
    Column('customer_id', String(256)),
    Column('customer_name', String(256)),
    Column('department_id', Text),
    Column('department_name', String(256)),
    Column('location_id', Text),
    Column('location_name', String(256)),
    Column('vendor_id', String),
    Column('vendor_name', String),
    Column('account_no', BigInteger),
    Column('account_title', String(256)),
    Column('class_id', Text),
    Column('class_name', Text),
    Column('created_at', DateTime(True)),
    Column('modified_at', DateTime(True)),
    Column('total_due', Double(53)),
    Column('total_entered', Double(53)),
    Column('total_paid', Double(53)),
    Column('number_of_items', BigInteger),
    Column('total_item_paid', Double(53)),
    Column('offset_gl_account_no', BigInteger),
    Column('offset_gl_account_title', String(256)),
    Column('record_id', String(256)),
    
)

t_sage_intacct__balance_sheet = Table(
    'sage_intacct__balance_sheet', metadata,
    Column('period_date', Date),
    Column('account_no', Text),
    Column('account_title', String),
    Column('account_type', String),
    Column('book_id', String(256)),
    Column('category', String),
    Column('classification', Text),
    Column('currency', String(256)),
    Column('entry_state', String(256)),
    Column('amount', Numeric),
    
)

t_sage_intacct__general_ledger = Table(
    'sage_intacct__general_ledger', metadata,
    Column('gl_detail_id', String(64)),
    Column('account_no', Text),
    Column('account_title', String(256)),
    Column('amount', Numeric),
    Column('book_id', String(256)),
    Column('credit_amount', Double(53)),
    Column('debit_amount', Double(53)),
    Column('currency', String(256)),
    Column('description', String(1024)),
    Column('doc_number', String(256)),
    Column('customer_id', String(256)),
    Column('customer_name', String(256)),
    Column('entry_date_at', Date),
    Column('entry_state', String(256)),
    Column('entry_description', String(512)),
    Column('line_no', BigInteger),
    Column('record_id', String(256)),
    Column('record_type', String(256)),
    Column('total_due', Double(53)),
    Column('total_entered', Double(53)),
    Column('total_paid', Double(53)),
    Column('tr_type', BigInteger),
    Column('trx_amount', Double(53)),
    Column('trx_credit_amount', Double(53)),
    Column('trx_debit_amount', Double(53)),
    Column('vendor_id', String(256)),
    Column('vendor_name', String(256)),
    Column('created_at', Date),
    Column('due_at', Date),
    Column('modified_at', DateTime(True)),
    Column('paid_at', Date),
    Column('category', String(256)),
    Column('classification', Text),
    Column('account_type', String(256)),
    Column('department_id', BigInteger),
    Column('location_id', String(256)),
    
)

t_sage_intacct__general_ledger_by_period = Table(
    'sage_intacct__general_ledger_by_period', metadata,
    Column('account_no', Text),
    Column('account_title', String(256)),
    Column('book_id', String(256)),
    Column('category', String(256)),
    Column('classification', Text),
    Column('currency', String(256)),
    Column('entry_state', String(256)),
    Column('account_type', String(256)),
    Column('date_year', Date),
    Column('period_first_day', Date),
    Column('period_last_day', Date),
    Column('period_net_amount', Numeric),
    Column('period_beg_amount', Numeric),
    Column('period_ending_amount', Numeric),
    
)

t_sage_intacct__profit_and_loss = Table(
    'sage_intacct__profit_and_loss', metadata,
    Column('period_date', Date),
    Column('account_no', Text),
    Column('account_title', String(256)),
    Column('account_type', String(256)),
    Column('book_id', String(256)),
    Column('category', String(256)),
    Column('classification', Text),
    Column('currency', String(256)),
    Column('entry_state', String(256)),
    Column('amount', Numeric),
    
)
