from sqlalchemy import BigInteger, Boolean, Column, Date, DateTime, Double, Float, MetaData, Numeric, PrimaryKeyConstraint, String, Table
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm.base import Mapped

metadata = MetaData()


t_account = Table(
    'account', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('description', String(256)),
    Column('fully_qualified_name', String(256)),
    Column('account_type', String(256)),
    Column('name', String(256)),
    Column('active', Boolean),
    Column('classification', String(256)),
    Column('sub_account', Boolean),
    Column('account_sub_type', String(256)),
    Column('sync_token', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('balance_with_sub_accounts', Numeric(21, 9)),
    Column('balance', Numeric(21, 9)),
    Column('account_number', String(256)),
    Column('parent_account_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='account_pkey'),
    
)

t_address = Table(
    'address', metadata,
    Column('id', String(256)),
    Column('line_1', String(256)),
    Column('line_2', String(256)),
    Column('line_3', String(256)),
    Column('line_4', String(256)),
    Column('line_5', String(256)),
    Column('city', String(256)),
    Column('postal_code', String(256)),
    Column('country', String(256)),
    Column('country_sub_division_code', String(256)),
    Column('latitude', String(256)),
    Column('longitude', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='address_pkey'),
    
)

t_bill = Table(
    'bill', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('home_balance', Numeric(21, 9)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('balance', Numeric(21, 9)),
    Column('private_note', String(256)),
    Column('doc_number', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('currency_id', String(256)),
    Column('due_date', Date),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_date', Date),
    Column('payable_account_id', String(256)),
    Column('sales_term_id', String(256)),
    Column('vendor_id', String(256)),
    Column('department_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='bill_pkey'),
    
)

t_bill_line = Table(
    'bill_line', metadata,
    Column('bill_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('item_expense_unit_price', Numeric(21, 9)),
    Column('item_expense_billable_status', String(256)),
    Column('item_expense_quantity', Numeric(38, 18)),
    Column('item_expense_tax_code_id', String(256)),
    Column('item_expense_item_id', String(256)),
    Column('item_expense_class_id', String(256)),
    Column('item_expense_customer_id', String(256)),
    Column('account_expense_billable_status', String(256)),
    Column('account_expense_tax_amount', Numeric(21, 9)),
    Column('account_expense_class_id', String(256)),
    Column('account_expense_tax_code_id', String(256)),
    Column('account_expense_account_id', String(256)),
    Column('account_expense_customer_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('bill_id', 'index', name='bill_line_pkey'),
    
)

t_bill_linked_txn = Table(
    'bill_linked_txn', metadata,
    Column('bill_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('bill_payment_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('bill_id', 'index', name='bill_linked_txn_pkey'),
    
)

t_bill_payment = Table(
    'bill_payment', metadata,
    Column('id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('pay_type', String(256)),
    Column('doc_number', String(256)),
    Column('sync_token', String(256)),
    Column('private_note', String(256)),
    Column('process_bill_payment', Boolean),
    Column('currency_id', String(256)),
    Column('credit_card_account_id', String(256)),
    Column('check_print_status', String(256)),
    Column('check_bank_account_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_date', Date),
    Column('department_id', String(256)),
    Column('vendor_id', String(256)),
    Column('payable_account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='bill_payment_pkey'),
    
)

t_bill_payment_line = Table(
    'bill_payment_line', metadata,
    Column('bill_payment_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('bill_id', String(256)),
    Column('vendor_credit_id', String(256)),
    Column('journal_entry_id', String(256)),
    Column('deposit_id', String(256)),
    Column('linked_bill_payment_id', String(256)),
    Column('expense_id', String(256)),
    Column('check_id', String(256)),
    Column('credit_card_charge_id', String(256)),
    Column('credit_card_credit_id', String(256)),
    Column('bill_payment_credit_card_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('bill_payment_id', 'index', name='bill_payment_line_pkey'),
    
)

t_budget = Table(
    'budget', metadata,
    Column('id', String(256)),
    Column('budget_type', String(256)),
    Column('name', String(256)),
    Column('budget_entry_type', String(256)),
    Column('sync_token', String(256)),
    Column('active', Boolean),
    Column('start_date', Date),
    Column('end_date', Date),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='budget_pkey'),
    
)

t_budget_detail = Table(
    'budget_detail', metadata,
    Column('budget_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(38, 18)),
    Column('budget_date', Date),
    Column('_fivetran_deleted', Boolean),
    Column('account_id', String(256)),
    Column('customer_id', String(256)),
    Column('class_id', String(256)),
    Column('department_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('budget_id', 'index', name='budget_detail_pkey'),
    
)

t_bundle = Table(
    'bundle', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('name', String(256)),
    Column('active', Boolean),
    Column('description', String(256)),
    Column('fully_qualified_name', String(256)),
    Column('taxable', Boolean),
    Column('unit_price', Numeric(21, 9)),
    Column('purchase_cost', Numeric(21, 9)),
    Column('print_grouped_items', Boolean),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='bundle_pkey'),
    
)

t_bundle_item = Table(
    'bundle_item', metadata,
    Column('bundle_id', String(256), nullable=False),
    Column('item_id', String(256), nullable=False),
    Column('item_quantity', Numeric(38, 18)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('bundle_id', 'item_id', name='bundle_item_pkey'),
    
)

t_class = Table(
    'class', metadata,
    Column('id', String(256)),
    Column('sub_class', Boolean),
    Column('sync_token', String(256)),
    Column('fully_qualified_name', String(256)),
    Column('name', String(256)),
    Column('active', Boolean),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('parent_class_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='class_pkey'),
    
)

t_credit_card_payment_txn = Table(
    'credit_card_payment_txn', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('amount', Numeric(38, 18)),
    Column('currency_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('transaction_date', Date),
    Column('bank_account_id', String(256)),
    Column('credit_card_account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='credit_card_payment_txn_pkey'),
    
)

t_credit_memo = Table(
    'credit_memo', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('email_status', String(256)),
    Column('remaining_credit', Numeric(21, 9)),
    Column('doc_number', String(256)),
    Column('print_status', String(256)),
    Column('sync_token', String(256)),
    Column('home_balance', Numeric(21, 9)),
    Column('private_note', String(256)),
    Column('balance', Numeric(21, 9)),
    Column('apply_tax_after_discount', Boolean),
    Column('global_tax_calculation', String(256)),
    Column('shipping_address_id', String(256)),
    Column('billing_address_id', String(256)),
    Column('bill_email', String(256)),
    Column('customer_memo', String(256)),
    Column('total_tax', Float),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('home_total_amount', Numeric(21, 9)),
    Column('transaction_date', Date),
    Column('customer_id', String(256)),
    Column('department_id', String(256)),
    Column('sales_term_id', String(256)),
    Column('class_id', String(256)),
    Column('payment_method_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='credit_memo_pkey'),
    
)

t_credit_memo_line = Table(
    'credit_memo_line', metadata,
    Column('credit_memo_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('sales_item_unit_price', Numeric(21, 9)),
    Column('sales_item_service_date', Date),
    Column('sales_item_discount_rate', Numeric(21, 9)),
    Column('sales_item_item_id', String(256)),
    Column('sales_item_class_id', String(256)),
    Column('sales_item_quantity', Numeric(21, 9)),
    Column('sales_item_account_id', String(256)),
    Column('sales_item_tax_code_id', String(256)),
    Column('sales_item_discount_amount', Numeric(21, 9)),
    Column('bundle_quantity', Numeric(21, 9)),
    Column('bundle_id', String(256)),
    Column('description_service_date', Date),
    Column('description_tax_code_id', String(256)),
    Column('discount_percent_based', Boolean),
    Column('discount_discount_percent', Numeric(21, 9)),
    Column('discount_account_id', String(256)),
    Column('discount_class_id', String(256)),
    Column('discount_tax_code_id', String(256)),
    Column('sub_total_item_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('credit_memo_id', 'index', name='credit_memo_line_pkey'),
    
)

t_credit_memo_line_bundle = Table(
    'credit_memo_line_bundle', metadata,
    Column('index', BigInteger, nullable=False),
    Column('line_num', BigInteger),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('unit_price', Numeric(21, 9)),
    Column('service_date', Date),
    Column('discount_rate', Numeric(21, 9)),
    Column('item_id', String(256)),
    Column('class_id', String(256)),
    Column('quantity', Numeric(21, 9)),
    Column('account_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('discount_amount', Numeric(21, 9)),
    Column('credit_memo_id', String(256), nullable=False),
    Column('credit_memo_line_index', BigInteger, nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('index', 'credit_memo_id', 'credit_memo_line_index', name='credit_memo_line_bundle_pkey'),
    
)

t_currency = Table(
    'currency', metadata,
    Column('id', String(256)),
    Column('name', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='currency_pkey'),
    
)

t_customer = Table(
    'customer', metadata,
    Column('id', String(256)),
    Column('family_name', String(256)),
    Column('fully_qualified_name', String(256)),
    Column('given_name', String(256)),
    Column('company_name', String(256)),
    Column('bill_with_parent', Boolean),
    Column('preferred_delivery_method', String(256)),
    Column('display_name', String(256)),
    Column('job', Boolean),
    Column('notes', String(256)),
    Column('print_on_check_name', String(256)),
    Column('title', String(256)),
    Column('middle_name', String(256)),
    Column('active', Boolean),
    Column('suffix', String(256)),
    Column('sync_token', String(256)),
    Column('level', BigInteger),
    Column('balance_with_jobs', Numeric(21, 9)),
    Column('balance', Numeric(21, 9)),
    Column('taxable', Boolean),
    Column('tax_exemption_reason_id', String(256)),
    Column('currency_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('email', String(256)),
    Column('website', String(256)),
    Column('phone_number', String(256)),
    Column('alternate_phone_number', String(256)),
    Column('open_balance_date', Date),
    Column('mobile_number', String(256)),
    Column('fax_number', String(256)),
    Column('shipping_address_id', String(256)),
    Column('bill_address_id', String(256)),
    Column('_fivetran_deleted', Boolean),
    Column('resale_number', String(256)),
    Column('customer_type_id', String(256)),
    Column('payment_method_id', String(256)),
    Column('parent_customer_id', String(256)),
    Column('default_tax_code_id', String(256)),
    Column('sales_term_id', String(256)),
    Column('ar_account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='customer_pkey'),
    
)

t_department = Table(
    'department', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('active', Boolean),
    Column('fully_qualified_name', String(256)),
    Column('sub_department', Boolean),
    Column('name', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('parent_department_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='department_pkey'),
    
)

t_deposit = Table(
    'deposit', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('private_note', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('currency_id', String(256)),
    Column('cash_back_amount', Numeric(38, 18)),
    Column('cash_back_memo', String(256)),
    Column('cash_back_account_id', String(256)),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('home_total_amount', Numeric(21, 9)),
    Column('transaction_status', String(256)),
    Column('transaction_source', String(256)),
    Column('transaction_date', Date),
    Column('department_id', String(256)),
    Column('account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='deposit_pkey'),
    
)

t_deposit_line = Table(
    'deposit_line', metadata,
    Column('deposit_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('detail_type', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('deposit_tax_applicable_on', String(256)),
    Column('deposit_check_number', String(256)),
    Column('deposit_transaction_type', String(256)),
    Column('deposit_tax_code_id', String(256)),
    Column('deposit_class_id', String(256)),
    Column('deposit_payment_method_id', String(256)),
    Column('deposit_account_id', String(256)),
    Column('deposit_customer_id', String(256)),
    Column('transfer_id', String(256)),
    Column('payment_id', String(256)),
    Column('sales_receipt_id', String(256)),
    Column('refund_receipt_id', String(256)),
    Column('journal_entry_id', String(256)),
    Column('expense_id', String(256)),
    Column('purchase_id', String(256)),
    Column('invoice_id', String(256)),
    Column('vendor_credit_id', String(256)),
    Column('bill_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('deposit_id', 'index', name='deposit_line_pkey'),
    
)

t_employee = Table(
    'employee', metadata,
    Column('id', String(256)),
    Column('organization', Boolean),
    Column('billable_time', Boolean),
    Column('family_name', String(256)),
    Column('given_name', String(256)),
    Column('gender', String(256)),
    Column('display_name', String(256)),
    Column('print_on_check_name', String(256)),
    Column('employee_number', String(256)),
    Column('title', String(256)),
    Column('middle_name', String(256)),
    Column('sync_token', String(256)),
    Column('active', Boolean),
    Column('suffix', String(256)),
    Column('bill_rate', Numeric(38, 18)),
    Column('hired_date', Date),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('address_id', String(256)),
    Column('phone_number', String(256)),
    Column('email', String(256)),
    Column('mobile_phone', String(256)),
    Column('released_date', Date),
    Column('birth_date', Date),
    Column('_fivetran_deleted', Boolean),
    Column('social_security_number', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='employee_pkey'),
    
)

t_estimate = Table(
    'estimate', metadata,
    Column('id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('email_status', String(256)),
    Column('doc_number', String(256)),
    Column('print_status', String(256)),
    Column('sync_token', String(256)),
    Column('apply_tax_after_discount', Boolean),
    Column('private_note', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('accepted_by', String(256)),
    Column('currency_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('delivery_type', String(256)),
    Column('bill_email', String(256)),
    Column('customer_memo', String(256)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('shipping_address_id', String(256)),
    Column('billing_address_id', String(256)),
    Column('due_date', Date),
    Column('ship_date', Date),
    Column('expiration_date', Date),
    Column('accepted_date', Date),
    Column('_fivetran_deleted', Boolean),
    Column('home_total_amount', Numeric(21, 9)),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_status', String(256)),
    Column('transaction_date', Date),
    Column('department_id', String(256)),
    Column('customer_id', String(256)),
    Column('class_id', String(256)),
    Column('sales_term_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='estimate_pkey'),
    
)

t_estimate_line = Table(
    'estimate_line', metadata,
    Column('estimate_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('sales_item_unit_price', Numeric(21, 9)),
    Column('sales_item_service_date', Date),
    Column('sales_item_discount_rate', Numeric(21, 9)),
    Column('sales_item_item_id', String(256)),
    Column('sales_item_class_id', String(256)),
    Column('sales_item_quantity', Numeric(21, 9)),
    Column('sales_item_account_id', String(256)),
    Column('sales_item_tax_code_id', String(256)),
    Column('sales_item_discount_amount', Numeric(21, 9)),
    Column('bundle_quantity', Numeric(21, 9)),
    Column('bundle_id', String(256)),
    Column('description_service_date', Date),
    Column('description_tax_code_id', String(256)),
    Column('discount_percent_based', Boolean),
    Column('discount_discount_percent', Numeric(21, 9)),
    Column('discount_account_id', String(256)),
    Column('discount_class_id', String(256)),
    Column('discount_tax_code_id', String(256)),
    Column('sub_total_item_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('estimate_id', 'index', name='estimate_line_pkey'),
    
)

t_estimate_line_bundle = Table(
    'estimate_line_bundle', metadata,
    Column('index', BigInteger, nullable=False),
    Column('line_num', BigInteger),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('unit_price', Numeric(21, 9)),
    Column('service_date', Date),
    Column('discount_rate', Numeric(21, 9)),
    Column('item_id', String(256)),
    Column('class_id', String(256)),
    Column('quantity', Numeric(21, 9)),
    Column('account_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('discount_amount', Numeric(21, 9)),
    Column('estimate_id', String(256), nullable=False),
    Column('estimate_line_index', BigInteger, nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('index', 'estimate_id', 'estimate_line_index', name='estimate_line_bundle_pkey'),
    
)

t_estimate_linked_txn = Table(
    'estimate_linked_txn', metadata,
    Column('estimate_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('invoice_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('estimate_id', 'index', name='estimate_linked_txn_pkey'),
    
)

t_estimate_tax_line = Table(
    'estimate_tax_line', metadata,
    Column('estimate_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('estimate_id', 'index', name='estimate_tax_line_pkey'),
    
)

t_invoice = Table(
    'invoice', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('email_status', String(256)),
    Column('allow_online_achpayment', Boolean),
    Column('allow_ipnpayment', Boolean),
    Column('doc_number', String(256)),
    Column('print_status', String(256)),
    Column('private_note', String(256)),
    Column('deposit', Numeric(21, 9)),
    Column('allow_online_payment', Boolean),
    Column('home_balance', Numeric(21, 9)),
    Column('allow_online_credit_card_payment', Boolean),
    Column('balance', Numeric(21, 9)),
    Column('apply_tax_after_discount', Boolean),
    Column('sync_token', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('delivery_time', Date),
    Column('delivery_type', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('billing_email', String(256)),
    Column('billing_cc_email', String(256)),
    Column('billing_bcc_email', String(256)),
    Column('customer_memo', String(256)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('shipping_address_id', String(256)),
    Column('billing_address_id', String(256)),
    Column('due_date', Date),
    Column('ship_date', Date),
    Column('_fivetran_deleted', Boolean),
    Column('tracking_number', String(256)),
    Column('home_total_amount', Numeric(21, 9)),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_source', String(256)),
    Column('transaction_date', Date),
    Column('department_id', String(256)),
    Column('sales_term_id', String(256)),
    Column('customer_id', String(256)),
    Column('class_id', String(256)),
    Column('deposit_to_account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='invoice_pkey'),
    
)

t_invoice_line = Table(
    'invoice_line', metadata,
    Column('invoice_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('id', String(256)),
    Column('line_num', BigInteger),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('detail_type', String(256)),
    Column('sales_item_unit_price', Numeric(21, 9)),
    Column('sales_item_service_date', Date),
    Column('sales_item_discount_rate', Numeric(21, 9)),
    Column('sales_item_item_id', String(256)),
    Column('sales_item_class_id', String(256)),
    Column('sales_item_quantity', Numeric(21, 9)),
    Column('sales_item_account_id', String(256)),
    Column('sales_item_tax_code_id', String(256)),
    Column('sales_item_discount_amount', Numeric(21, 9)),
    Column('bundle_quantity', Numeric(21, 9)),
    Column('bundle_id', String(256)),
    Column('description_service_date', Date),
    Column('description_tax_code_id', String(256)),
    Column('discount_percent_based', Boolean),
    Column('discount_discount_percent', Numeric(21, 9)),
    Column('discount_account_id', String(256)),
    Column('discount_class_id', String(256)),
    Column('discount_tax_code_id', String(256)),
    Column('sub_total_item_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('invoice_id', 'index', name='invoice_line_pkey'),
    
)

t_invoice_line_bundle = Table(
    'invoice_line_bundle', metadata,
    Column('index', BigInteger, nullable=False),
    Column('line_num', BigInteger),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('unit_price', Numeric(21, 9)),
    Column('service_date', Date),
    Column('discount_rate', Numeric(21, 9)),
    Column('item_id', String(256)),
    Column('class_id', String(256)),
    Column('quantity', Numeric(21, 9)),
    Column('account_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('discount_amount', Numeric(21, 9)),
    Column('invoice_id', String(256), nullable=False),
    Column('invoice_line_index', BigInteger, nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('index', 'invoice_id', 'invoice_line_index', name='invoice_line_bundle_pkey'),
    
)

t_invoice_linked_txn = Table(
    'invoice_linked_txn', metadata,
    Column('invoice_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('payment_id', String(256)),
    Column('reimburse_charge_id', String(256)),
    Column('charge_credit_id', String(256)),
    Column('statement_charge_id', String(256)),
    Column('estimate_id', String(256)),
    Column('time_activity_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('invoice_id', 'index', name='invoice_linked_txn_pkey'),
    
)

t_invoice_tax_line = Table(
    'invoice_tax_line', metadata,
    Column('invoice_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('invoice_id', 'index', name='invoice_tax_line_pkey'),
    
)

t_item = Table(
    'item', metadata,
    Column('id', String(256)),
    Column('description', String(256)),
    Column('fully_qualified_name', String(256)),
    Column('name', String(256)),
    Column('sync_token', String(256)),
    Column('active', Boolean),
    Column('unit_price', Numeric(38, 18)),
    Column('type', String(256)),
    Column('purchase_cost', Numeric(38, 18)),
    Column('taxable', Boolean),
    Column('sub_item', Boolean),
    Column('level', BigInteger),
    Column('sales_tax_included', Boolean),
    Column('purchase_tax_included', Boolean),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('stock_keeping_unit', String(256)),
    Column('purchase_description', String(256)),
    Column('quantity_on_hand', Numeric(38, 18)),
    Column('track_quantity_on_hand', Boolean),
    Column('inventory_start_date', Date),
    Column('asset_account_id', String(256)),
    Column('income_account_id', String(256)),
    Column('expense_account_id', String(256)),
    Column('parent_item_id', String(256)),
    Column('sales_tax_code_id', String(256)),
    Column('purchase_tax_code_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='item_pkey'),
    
)

t_journal_entry = Table(
    'journal_entry', metadata,
    Column('id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('adjustment', Boolean),
    Column('doc_number', String(256)),
    Column('sync_token', String(256)),
    Column('private_note', String(256)),
    Column('currency_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('home_total_amount', Numeric(21, 9)),
    Column('transaction_date', Date),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='journal_entry_pkey'),
    
)

t_journal_entry_line = Table(
    'journal_entry_line', metadata,
    Column('journal_entry_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('posting_type', String(256)),
    Column('customer_id', String(256)),
    Column('vendor_id', String(256)),
    Column('employee_id', String(256)),
    Column('tax_applicable_on', String(256)),
    Column('tax_amount', Numeric(21, 9)),
    Column('billable_status', String(256)),
    Column('class_id', String(256)),
    Column('account_id', String(256)),
    Column('department_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('description_service_date', Date),
    Column('description_tax_code_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('journal_entry_id', 'index', name='journal_entry_line_pkey'),
    
)

t_journal_entry_tax_line = Table(
    'journal_entry_tax_line', metadata,
    Column('journal_entry_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('journal_entry_id', 'index', name='journal_entry_tax_line_pkey'),
    
)

t_payment = Table(
    'payment', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('process_payment', Boolean),
    Column('sync_token', String(256)),
    Column('private_note', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('credit_card_type', String(256)),
    Column('credit_card_cc_expiry_month', BigInteger),
    Column('credit_card_cc_expiry_year', BigInteger),
    Column('credit_card_postal_code', String(256)),
    Column('credit_card_amount', Numeric(21, 9)),
    Column('credit_card_process_payment', Boolean),
    Column('credit_card_name_on_account', String(256)),
    Column('credit_card_billing_address_street', String(256)),
    Column('credit_card_cctrans_id', String(256)),
    Column('credit_card_auth_code', String(256)),
    Column('credit_card_status', String(256)),
    Column('credit_card_transaction_authorization_time', Date),
    Column('_fivetran_deleted', Boolean),
    Column('reference_number', String(256)),
    Column('unapplied_amount', Numeric(21, 9)),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_date', Date),
    Column('transaction_status', String(256)),
    Column('transaction_source', String(256)),
    Column('receivable_account_id', String(256)),
    Column('payment_method_id', String(256)),
    Column('customer_id', String(256)),
    Column('deposit_to_account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='payment_pkey'),
    
)

t_payment_line = Table(
    'payment_line', metadata,
    Column('payment_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('expense_id', String(256)),
    Column('check_id', String(256)),
    Column('credit_card_credit_id', String(256)),
    Column('credit_card_charge_id', String(256)),
    Column('journal_entry_id', String(256)),
    Column('credit_memo_id', String(256)),
    Column('invoice_id', String(256)),
    Column('deposit_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('payment_id', 'index', name='payment_line_pkey'),
    
)

t_payment_method = Table(
    'payment_method', metadata,
    Column('id', String(256)),
    Column('name', String(256)),
    Column('active', Boolean),
    Column('type', String(256)),
    Column('sync_token', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='payment_method_pkey'),
    
)

t_purchase = Table(
    'purchase', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('sync_token', String(256)),
    Column('credit', Boolean),
    Column('doc_number', String(256)),
    Column('payment_type', String(256)),
    Column('print_status', String(256)),
    Column('private_note', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('customer_id', String(256)),
    Column('vendor_id', String(256)),
    Column('employee_id', String(256)),
    Column('remit_to_address_id', String(256)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_date', Date),
    Column('transaction_source', String(256)),
    Column('account_id', String(256)),
    Column('department_id', String(256)),
    Column('payment_method_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='purchase_pkey'),
    
)

t_purchase_line = Table(
    'purchase_line', metadata,
    Column('purchase_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('description', String(256)),
    Column('item_expense_unit_price', Numeric(21, 9)),
    Column('item_expense_billable_status', String(256)),
    Column('item_expense_quantity', Numeric(38, 18)),
    Column('item_expense_tax_code_id', String(256)),
    Column('item_expense_item_id', String(256)),
    Column('item_expense_class_id', String(256)),
    Column('item_expense_customer_id', String(256)),
    Column('account_expense_billable_status', String(256)),
    Column('account_expense_tax_amount', Numeric(21, 9)),
    Column('account_expense_class_id', String(256)),
    Column('account_expense_tax_code_id', String(256)),
    Column('account_expense_account_id', String(256)),
    Column('account_expense_customer_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('purchase_id', 'index', name='purchase_line_pkey'),
    
)

t_purchase_order = Table(
    'purchase_order', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('sync_token', String(256)),
    Column('doc_number', String(256)),
    Column('private_note', String(256)),
    Column('memo', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('due_date', Date),
    Column('vendor_address_id', String(256)),
    Column('shipping_address_id', String(256)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('_fivetran_deleted', Boolean),
    Column('status', String(256)),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_date', Date),
    Column('payable_account_id', String(256)),
    Column('vendor_id', String(256)),
    Column('class_id', String(256)),
    Column('sales_term_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='purchase_order_pkey'),
    
)

t_purchase_order_line = Table(
    'purchase_order_line', metadata,
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('item_expense_unit_price', Numeric(21, 9)),
    Column('item_expense_billable_status', String(256)),
    Column('item_expense_quantity', Numeric(38, 18)),
    Column('item_expense_tax_code_id', String(256)),
    Column('item_expense_item_id', String(256)),
    Column('item_expense_class_id', String(256)),
    Column('item_expense_customer_id', String(256)),
    Column('account_expense_billable_status', String(256)),
    Column('account_expense_tax_amount', Numeric(21, 9)),
    Column('account_expense_class_id', String(256)),
    Column('account_expense_tax_code_id', String(256)),
    Column('account_expense_account_id', String(256)),
    Column('account_expense_customer_id', String(256)),
    Column('purchase_order_id', String(256), nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('index', 'purchase_order_id', name='purchase_order_line_pkey'),
    
)

t_purchase_order_linked_txn = Table(
    'purchase_order_linked_txn', metadata,
    Column('purchase_order_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('bill_id', String(256)),
    Column('purchase_id', String(256)),
    Column('vendor_credit_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('purchase_order_id', 'index', name='purchase_order_linked_txn_pkey'),
    
)

t_purchase_order_tax_line = Table(
    'purchase_order_tax_line', metadata,
    Column('purchase_order_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('purchase_order_id', 'index', name='purchase_order_tax_line_pkey'),
    
)

t_purchase_tax_line = Table(
    'purchase_tax_line', metadata,
    Column('purchase_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(38, 18)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('purchase_id', 'index', name='purchase_tax_line_pkey'),
    
)

t_refund_receipt = Table(
    'refund_receipt', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('doc_number', String(256)),
    Column('home_balance', Numeric(21, 9)),
    Column('print_status', String(256)),
    Column('balance', Numeric(21, 9)),
    Column('apply_tax_after_discount', Boolean),
    Column('private_note', String(256)),
    Column('payment_type', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('currency_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('bill_email', String(256)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('customer_memo', String(256)),
    Column('billing_address_id', String(256)),
    Column('shipping_address_id', String(256)),
    Column('check_payment_status', String(256)),
    Column('check_payment_bank_name', String(256)),
    Column('check_payment_check_number', String(256)),
    Column('check_payment_name_on_account', String(256)),
    Column('check_payment_account_number', String(256)),
    Column('credit_card_type', String(256)),
    Column('credit_card_cc_expiry_month', BigInteger),
    Column('credit_card_cc_expiry_year', BigInteger),
    Column('credit_card_postal_code', String(256)),
    Column('credit_card_amount', Numeric(21, 9)),
    Column('credit_card_process_payment', Boolean),
    Column('credit_card_name_on_account', String(256)),
    Column('credit_card_billing_address_street', String(256)),
    Column('credit_card_cctrans_id', String(256)),
    Column('credit_card_auth_code', String(256)),
    Column('credit_card_status', String(256)),
    Column('credit_card_transaction_authorization_time', Date),
    Column('_fivetran_deleted', Boolean),
    Column('payment_reference_number', String(256)),
    Column('total_amount', Numeric(38, 18)),
    Column('home_total_amount', Numeric(21, 9)),
    Column('transaction_date', Date),
    Column('transaction_source', String(256)),
    Column('deposit_to_account_id', String(256)),
    Column('department_id', String(256)),
    Column('payment_method_id', String(256)),
    Column('customer_id', String(256)),
    Column('class_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='refund_receipt_pkey'),
    
)

t_refund_receipt_line = Table(
    'refund_receipt_line', metadata,
    Column('refund_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('sales_item_unit_price', Numeric(21, 9)),
    Column('sales_item_service_date', Date),
    Column('sales_item_discount_rate', Numeric(21, 9)),
    Column('sales_item_item_id', String(256)),
    Column('sales_item_class_id', String(256)),
    Column('sales_item_quantity', Numeric(21, 9)),
    Column('sales_item_account_id', String(256)),
    Column('sales_item_tax_code_id', String(256)),
    Column('sales_item_discount_amount', Numeric(21, 9)),
    Column('bundle_quantity', Numeric(21, 9)),
    Column('bundle_id', String(256)),
    Column('description_service_date', Date),
    Column('description_tax_code_id', String(256)),
    Column('discount_percent_based', Boolean),
    Column('discount_discount_percent', Numeric(21, 9)),
    Column('discount_account_id', String(256)),
    Column('discount_class_id', String(256)),
    Column('discount_tax_code_id', String(256)),
    Column('sub_total_item_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('refund_id', 'index', name='refund_receipt_line_pkey'),
    
)

t_refund_receipt_line_bundle = Table(
    'refund_receipt_line_bundle', metadata,
    Column('index', BigInteger, nullable=False),
    Column('line_num', BigInteger),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('unit_price', Numeric(21, 9)),
    Column('service_date', Date),
    Column('discount_rate', Numeric(21, 9)),
    Column('item_id', String(256)),
    Column('class_id', String(256)),
    Column('quantity', Numeric(21, 9)),
    Column('account_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('discount_amount', Numeric(21, 9)),
    Column('refund_receipt_id', String(256), nullable=False),
    Column('refund_receipt_line_index', BigInteger, nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('index', 'refund_receipt_id', 'refund_receipt_line_index', name='refund_receipt_line_bundle_pkey'),
    
)

t_refund_receipt_tax_line = Table(
    'refund_receipt_tax_line', metadata,
    Column('refund_receipt_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('refund_receipt_id', 'index', name='refund_receipt_tax_line_pkey'),
    
)

t_sales_receipt = Table(
    'sales_receipt', metadata,
    Column('id', String(256)),
    Column('currency_id', String(256)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('email_status', String(256)),
    Column('doc_number', String(256)),
    Column('print_status', String(256)),
    Column('balance', Numeric(21, 9)),
    Column('apply_tax_after_discount', Boolean),
    Column('home_balance', Numeric(21, 9)),
    Column('sync_token', String(256)),
    Column('private_note', String(256)),
    Column('global_tax_calculation', String(256)),
    Column('shipping_address_id', String(256)),
    Column('billing_address_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('bill_email', String(256)),
    Column('customer_memo', String(256)),
    Column('total_tax', Numeric(21, 9)),
    Column('tax_code_id', String(256)),
    Column('ship_date', Date),
    Column('delivery_time', Date),
    Column('delivery_type', String(256)),
    Column('credit_card_type', String(256)),
    Column('credit_card_cc_expiry_month', BigInteger),
    Column('credit_card_cc_expiry_year', BigInteger),
    Column('credit_card_postal_code', String(256)),
    Column('credit_card_amount', Numeric(21, 9)),
    Column('credit_card_process_payment', Boolean),
    Column('credit_card_name_on_account', String(256)),
    Column('credit_card_billing_address_street', String(256)),
    Column('credit_card_cctrans_id', String(256)),
    Column('credit_card_auth_code', String(256)),
    Column('credit_card_status', String(256)),
    Column('credit_card_transaction_authorization_time', Date),
    Column('_fivetran_deleted', Boolean),
    Column('tracking_number', String(256)),
    Column('payment_reference_number', String(256)),
    Column('home_total_amount', Numeric(21, 9)),
    Column('total_amount', Numeric(38, 18)),
    Column('payment_method_id', String(256)),
    Column('transaction_date', Date),
    Column('transaction_source', String(256)),
    Column('deposit_to_account_id', String(256)),
    Column('customer_id', String(256)),
    Column('department_id', String(256)),
    Column('class_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='sales_receipt_pkey'),
    
)

t_sales_receipt_line = Table(
    'sales_receipt_line', metadata,
    Column('sales_receipt_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('sales_item_unit_price', Numeric(21, 9)),
    Column('sales_item_service_date', Date),
    Column('sales_item_discount_rate', Numeric(21, 9)),
    Column('sales_item_item_id', String(256)),
    Column('sales_item_class_id', String(256)),
    Column('sales_item_quantity', Numeric(21, 9)),
    Column('sales_item_account_id', String(256)),
    Column('sales_item_tax_code_id', String(256)),
    Column('sales_item_discount_amount', Numeric(21, 9)),
    Column('bundle_quantity', Numeric(21, 9)),
    Column('bundle_id', String(256)),
    Column('description_service_date', Date),
    Column('description_tax_code_id', String(256)),
    Column('discount_percent_based', Boolean),
    Column('discount_discount_percent', Numeric(21, 9)),
    Column('discount_account_id', String(256)),
    Column('discount_class_id', String(256)),
    Column('discount_tax_code_id', String(256)),
    Column('sub_total_item_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('sales_receipt_id', 'index', name='sales_receipt_line_pkey'),
    
)

t_sales_receipt_line_bundle = Table(
    'sales_receipt_line_bundle', metadata,
    Column('index', BigInteger, nullable=False),
    Column('line_num', BigInteger),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('unit_price', Numeric(21, 9)),
    Column('service_date', Date),
    Column('discount_rate', Numeric(21, 9)),
    Column('item_id', String(256)),
    Column('class_id', String(256)),
    Column('quantity', Numeric(21, 9)),
    Column('account_id', String(256)),
    Column('tax_code_id', String(256)),
    Column('discount_amount', Numeric(21, 9)),
    Column('sales_receipt_id', String(256), nullable=False),
    Column('sales_receipt_line_index', BigInteger, nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('index', 'sales_receipt_id', 'sales_receipt_line_index', name='sales_receipt_line_bundle_pkey'),
    
)

t_sales_receipt_tax_line = Table(
    'sales_receipt_tax_line', metadata,
    Column('sales_receipt_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('amount', Numeric(21, 9)),
    Column('percent_based', Boolean),
    Column('net_amount_taxable', Numeric(21, 9)),
    Column('tax_inclusive_amount', Numeric(21, 9)),
    Column('override_delta_amount', Numeric(21, 9)),
    Column('tax_percent', Numeric(21, 9)),
    Column('tax_rate_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('sales_receipt_id', 'index', name='sales_receipt_tax_line_pkey'),
    
)

t_tax_agency = Table(
    'tax_agency', metadata,
    Column('id', String(256)),
    Column('tax_tracked_on_purchases', Boolean),
    Column('sync_token', String(256)),
    Column('display_name', String(256)),
    Column('tax_tracked_on_sales', Boolean),
    Column('tax_registration_number', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='tax_agency_pkey'),
    
)

t_tax_code = Table(
    'tax_code', metadata,
    Column('id', String(256)),
    Column('active', Boolean),
    Column('description', String(256)),
    Column('name', String(256)),
    Column('taxable', Boolean),
    Column('tax_group', Boolean),
    Column('sync_token', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='tax_code_pkey'),
    
)

t_tax_rate = Table(
    'tax_rate', metadata,
    Column('id', String(256)),
    Column('name', String(256)),
    Column('special_tax_type', String(256)),
    Column('active', Boolean),
    Column('rate_value', Numeric(38, 18)),
    Column('description', String(256)),
    Column('display_type', String(256)),
    Column('sync_token', String(256)),
    Column('effective_tax_rate', JSONB),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('tax_agency_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='tax_rate_pkey'),
    
)

t_tax_rate_detail = Table(
    'tax_rate_detail', metadata,
    Column('tax_code_id', String(256), nullable=False),
    Column('type', String(256)),
    Column('tax_type_applicable', String(256)),
    Column('tax_order', BigInteger),
    Column('_fivetran_deleted', Boolean),
    Column('tax_rate_id', String(256), nullable=False),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('tax_code_id', 'tax_rate_id', name='tax_rate_detail_pkey'),
    
)

t_term = Table(
    'term', metadata,
    Column('id', String(256)),
    Column('discount_days', BigInteger),
    Column('discount_percent', Numeric(21, 9)),
    Column('name', String(256)),
    Column('active', Boolean),
    Column('type', String(256)),
    Column('due_days', BigInteger),
    Column('sync_token', String(256)),
    Column('day_of_month_due', BigInteger),
    Column('due_next_month_days', BigInteger),
    Column('discount_day_of_month', BigInteger),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='term_pkey'),
    
)

t_time_activity = Table(
    'time_activity', metadata,
    Column('id', String(256)),
    Column('name_of', String(256)),
    Column('description', String(256)),
    Column('hours', Double(53)),
    Column('break_hours', Double(53)),
    Column('hourly_rate', Numeric(24, 11)),
    Column('minutes', Double(53)),
    Column('break_minutes', Double(53)),
    Column('billable_status', String(256)),
    Column('sync_token', String(256)),
    Column('taxable', Boolean),
    Column('start_time', DateTime(True)),
    Column('end_time', DateTime(True)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('transaction_date', Date),
    Column('employee_id', String(256)),
    Column('item_id', String(256)),
    Column('customer_id', String(256)),
    Column('department_id', String(256)),
    Column('vendor_id', String(256)),
    Column('class_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='time_activity_pkey'),
    
)

t_transfer = Table(
    'transfer', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('private_note', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('transaction_date', Date),
    Column('to_account_id', String(256)),
    Column('from_account_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='transfer_pkey'),
    
)

t_vendor = Table(
    'vendor', metadata,
    Column('id', String(256)),
    Column('vendor_1099', Boolean),
    Column('family_name', String(256)),
    Column('tax_identifier', String(256)),
    Column('given_name', String(256)),
    Column('company_name', String(256)),
    Column('active', Boolean),
    Column('suffix', String(256)),
    Column('balance', Numeric(21, 9)),
    Column('display_name', String(256)),
    Column('print_on_check_name', String(256)),
    Column('title', String(256)),
    Column('middle_name', String(256)),
    Column('sync_token', String(256)),
    Column('email', String(256)),
    Column('web_url', String(256)),
    Column('alternate_phone', String(256)),
    Column('primary_phone', String(256)),
    Column('mobile_phone', String(256)),
    Column('fax_number', String(256)),
    Column('billing_address_id', String(256)),
    Column('currency_id', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('_fivetran_deleted', Boolean),
    Column('account_number', String(256)),
    Column('term_id', String(256)),
    Column('other_contacts', JSONB),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='vendor_pkey'),
    
)

t_vendor_credit = Table(
    'vendor_credit', metadata,
    Column('id', String(256)),
    Column('sync_token', String(256)),
    Column('doc_number', String(256)),
    Column('private_note', String(256)),
    Column('balance', Numeric(21, 9)),
    Column('exchange_rate', Numeric(21, 9)),
    Column('global_tax_calculation', String(256)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('currency_id', String(256)),
    Column('_fivetran_deleted', Boolean),
    Column('total_amount', Numeric(38, 18)),
    Column('transaction_date', Date),
    Column('payable_account_id', String(256)),
    Column('vendor_id', String(256)),
    Column('department_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('id', name='vendor_credit_pkey'),
    
)

t_vendor_credit_line = Table(
    'vendor_credit_line', metadata,
    Column('vendor_credit_id', String(256), nullable=False),
    Column('index', BigInteger, nullable=False),
    Column('description', String(256)),
    Column('amount', Numeric(21, 9)),
    Column('private_note', String(256)),
    Column('item_expense_unit_price', Numeric(21, 9)),
    Column('item_expense_billable_status', String(256)),
    Column('item_expense_quantity', Numeric(38, 18)),
    Column('item_expense_tax_code_id', String(256)),
    Column('item_expense_item_id', String(256)),
    Column('item_expense_class_id', String(256)),
    Column('item_expense_customer_id', String(256)),
    Column('account_expense_billable_status', String(256)),
    Column('account_expense_tax_amount', Numeric(21, 9)),
    Column('account_expense_class_id', String(256)),
    Column('account_expense_tax_code_id', String(256)),
    Column('account_expense_account_id', String(256)),
    Column('account_expense_customer_id', String(256)),
    Column('_fivetran_synced', DateTime(True)),
    PrimaryKeyConstraint('vendor_credit_id', 'index', name='vendor_credit_line_pkey'),
    
)
